# Generated by Django 4.2.2 on 2023-06-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ('id',)},
        ),
    ]
