# Generated by Django 4.2.2 on 2023-07-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_stockdata_logreturns_remove_stockdata_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='TrainedOn',
            field=models.CharField(default='RELIANCE.NS', max_length=50),
            preserve_default=False,
        ),
    ]
