# Generated by Django 4.2.2 on 2023-07-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stockinfo_trainedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='Residue',
            field=models.FloatField(default=25.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='Seasonal',
            field=models.FloatField(default=25.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='Trend',
            field=models.FloatField(default=25.0),
            preserve_default=False,
        ),
    ]
