# Generated by Django 4.2.2 on 2023-07-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stockdata_bollbottom_stockdata_bolltop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='DateString',
            field=models.CharField(default='just', max_length=25),
            preserve_default=False,
        ),
    ]
