# Generated by Django 4.2.2 on 2023-07-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_stockdata_datestring'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='RSI',
            field=models.FloatField(default=50.0),
            preserve_default=False,
        ),
    ]
