# Generated by Django 4.2.2 on 2023-07-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_stockdata_rsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='MACDhist',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
    ]
