# Generated by Django 4.2.2 on 2023-07-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_stockdata_macdhist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PubDate', models.DateField()),
                ('Title', models.CharField(max_length=250)),
                ('Link', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
